//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VP : DbContext
    {
        public VP()
            : base("name=VP")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<customer> customer { get; set; }
        public virtual DbSet<customer_order> customer_order { get; set; }
        public virtual DbSet<manufacturer> manufacturer { get; set; }
        public virtual DbSet<order_details> order_details { get; set; }
        public virtual DbSet<order_status> order_status { get; set; }
        public virtual DbSet<product> product { get; set; }
        public virtual DbSet<product_amount> product_amount { get; set; }
        public virtual DbSet<product_category> product_category { get; set; }
        public virtual DbSet<user> user { get; set; }
    }
}
