//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_details
    {
        public int id { get; set; }
        public int customer_order_id { get; set; }
        public int product_id { get; set; }
        public decimal price { get; set; }
        public decimal price_with_discount { get; set; }
        public Nullable<int> product_amount { get; set; }
    
        public virtual customer_order customer_order { get; set; }
        public virtual product product { get; set; }
    }
}
