//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CourseProject
{
    using System;
    using System.Collections.Generic;
    
    public partial class person_contact
    {
        public int id { get; set; }
        public int contact_type_id { get; set; }
        public int person_id { get; set; }
        public string person_contact_value { get; set; }
    
        public virtual contact_type contact_type { get; set; }
        public virtual person person { get; set; }
    }
}
